structure(list(url = "https://training.datim.org/api/33/sqlViews/fgUtV6e9YIX/data.csv?paging=false", 
    status_code = 401L, headers = structure(list(server = "nginx", 
        date = "Mon, 22 Mar 2021 16:19:04 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-length` = "92", `strict-transport-security` = "max-age=31536000 ; includeSubDomains", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=63072000; includeSubdomains; preload"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 22 Mar 2021 16:19:04 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `content-length` = "92", `strict-transport-security` = "max-age=31536000 ; includeSubDomains", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=63072000; includeSubdomains; preload"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"httpStatus\":\"Unauthorized\",\"httpStatusCode\":401,\"status\":\"ERROR\",\"message\":\"Unauthorized\"}"), 
    date = structure(1616429944, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.113979, 
    connect = 0.182321, pretransfer = 0.334368, starttransfer = 0.418834, 
    total = 0.418875)), class = "response")
