#' @docType package
#' @name datapackr
#' @title Data Pack on R
#'
#' datapackr: a grammar of Data Pack manipulation
#'
#'
#' datapackr is the engine behind PEPFAR Data Packs, a tool used annually to
#' aid PEPFAR Country Teams in setting targets for their annual Country
#' Operating Plan (COP).
#'
#' It has three main goals:
#'
#' \itemize{
#' \item Generate Data Packs, either at District or Site Level as directed.
#' \item Process and validate Data Packs submitted for review
#' \item Prepare Data Pack data for import into DATIM, the PEPFAR data collection database.
#' }
#'
#'

if (getRversion() >= "2.15.1")
  utils::globalVariables(
    c(
########## Will throw error if not included below ###########
      "cop21_data_pack_schema",
      "is_valid",
      "PMTCT_EID.N.12.T",
      "PMTCT_EID.N.2.T",
      "PMTCT_EID.T",
      "PMTCT_EID.2mo.rate",
      "HTS_INDEX_COM.New.Pos.T",
      "HTS_INDEX_FAC.New.Pos.T",
      "index_issues",
      "HTS_TST.KP.Linkage.T",
      "TX_NEW.T",
      "HTS_TST.KP.Pos.T",
      "TX_NEW.KP.T",
      "PMTCT_STAT.N.New.Pos.T",
      "PMTCT_STAT.N.KnownPos.T",
      "PMTCT_STAT.N.New.Neg.T",
      "PMTCT_STAT.N.Total",
      "knownpos_ratio",
      "TX_CURR.T",
      "TX_CURR.T_1",
      "TX_NEW.T",
      "TB_STAT.N.New.Pos.T",
      "TB_STAT.N.KnownPos.T",
      "TB_STAT.N.New.Neg.T",
      "TB_STAT.N.Total",
      "knownpos_ratio",
      "VMMC_CIRC.Pos.T",
      "VMMC_CIRC.Neg.T",
      "VMMC_CIRC.Unk.T",
      "VMMC_CIRC.T",
      "VMMC_CIRC.indeterminateRate",
      "distribution_diff",
      "DSD",
      "TA",
      "total_distribution",
      "key_population",
      "target_value",
      "schema",
      "home_cell",
      "area_id",
      "calendar_quarter",
      "age_uid",
      "sex_uid",
      "POP_EST.T_1",
      "PLHIV.T_1",
      "TX_CURR_SUBNAT.T_1",
      "pop",
      "plhiv",
      "tx_curr",
      "period_dataset",
      "d2_session",
      "organisationUnitGroups",
      "data_element.name",
      "data_element.id",
      "category_combo.name",
      "category_combo.id",
      "category_option.name",
      "category_option.id",
      "d2_default_session",
      "V1",
      "target_col",
      "id_col",
      "cop_year",
      "attribute_option",
      "Total Duplicated Rollup",
      "Total Duplicated Rollup.updated",
      "DSD Duplicated Rollup.updated",
      "TA Duplicated Rollup.updated",
      "DSD Dedupe.updated",
      "TA Dedupe.updated",
      "Crosswalk Dedupe.updated",
      "DREAMS_SNU.Flag",
      "mechcode_supporttype", 
      "age_option_name",
      "sex_option_name",
      "kp_option_name",
      "DSD Dedupe",
      "TA Dedupe",
      "Crosswalk Dedupe",
      "Custom DSD Dedupe Allocation (FY22) (% of DataPackTarget)",
      "Custom TA Dedupe Allocation (FY22) (% of DataPackTarget)",
      "Custom Crosswalk Dedupe Allocation (FY22) (% of DataPackTarget)",
      "DSD Dedupe Resolution (FY22)",
      "TA Dedupe Resolution (FY22)",
      "Crosswalk Dedupe Resolution (FY22)",
      "dataSets",
      "DataPack",
      "DATIM",
       "col_name",
      "col_name_new",
      "duplicate_cols",
       "TA Duplicated Rollup",
       "DSD Duplicated Rollup",
       "Deduplicated DSD Rollup",
       "Deduplicated TA Rollup",
       "Total Deduplicated Rollup",
       "Max Total Deduplicated Rollup",
       "Min Deduplicated DSD Rollup",
       "Max Deduplicated DSD Rollup",
       "Min Deduplicated TA Rollup",
       "Max Deduplicated TA Rollup",
       "Min Total Deduplicated Rollup",
       "col_name",
       "col_name_new",
       "duplicate_cols",
       "TA Duplicated Rollup",
       "DSD Duplicated Rollup",
       "Deduplicated DSD Rollup (FY22)",
       "Deduplicated TA Rollup (FY22)",
       "SUM - DSD",
       "SUM - TA",
       "Total Deduplicated Rollup (FY22)",
       "SUM - Crosswalk Total",
      "PSNUxIM_value",
      "warn",
      "MAX - DSD",
      "MAX - TA",
      "MAX - Crosswalk Total",
      "issues.Deduplicated DSD Rollup",
      "issues.Deduplicated TA Rollup",
      "issues.Total Deduplicated Rollup",
      "DSD_count",
      "TA_count",
      "Total_count",
      "as",
      
      

 ########### The Below need tested ######     
      ".GRP",
      ".",
      "age",
      "Age",
      "age_option_uid",
      "AgeCoarse",
      "agency",
      "ancestors",
      "ART_coverage",
      "ART_coverage.psnu",
      "attribute_option_combo",
      "attribute_option_combo_code",
      "attributeoptioncombo",
      "attributeOptionCombo",
      "attributeOptionCombo.y",
      "category",
      "category_option_combo",
      "category_option_combo_uid",
      "categoryoption",
      "categoryoption_specified",
      "categoryoptioncombo",
      "categoryOptionCombo",
      "categoryoptioncomboname",
      "categoryoptioncombo_id",
      "categoryoptioncombo_name",
      "categoryoptioncombouid",
      "categoryoptiongroup",
      "categoryOptions",
      "character_10",
      "character_11",
      "character_12",
      "character_13",
      "character_14",
      "character_5",
      "character_6",
      "character_7",
      "character_8",
      "character_9",
      "code",
      "col_type",
      "cop20_data_pack_schema",
      "correct_fx",
      "count",
      "country",
      "country_name",
      "country_uid",
      "country_uids",
      "data_element",
      "data_element_uid",
      "data_pack_name",
      "data_stream",
      "data_structure",
      "dataElement",
      "dataelement",
      "dataelement_dsd",
      "dataelementname",
      "dataelement_ta",
      "dataelement.y",
      "dataelementuid",
      "datapack_cog",
      "datapack_disagg",
      "DataPack_name",
      "datapack_schema_group",
      "datapack_value",
      "DataPackTarget",
      "dataset",
      "datim_value",
      "Dedupe",
      "defunct",
      "delta",
      "diffRounded",
      "disagg_type",
      "displayName",
      "distributed_value",
      "distributed_value_rounded",
      "distributed_value_rounded_total",
      "distributed_value_total",
      "distribution",
      "distribution_numeric",
      "dp",
      "dp_psnu",
      "DREAMS",
      "duplicated_cols",
      "duplicates",
      "effect",
      "enddate",
      "fiscal_year",
      "formula",
      "formula_15",
      "formula_diff",
      "formula.x",
      "formula.y",
      "funding_agency",
      "FY",
      "group",
      "grp",
      "HTS_INDEX_COM.N.Age_Sex_Result.T.NewPos",
      "HTS_INDEX_FAC.N.Age_Sex_Result.T.NewPos",
      "HTS_INDEX.total",
      "hts_modality",
      "HTS_TST_EmergencyWard.N.Age_Sex_Result.T.Positive",
      "HTS_TST_Inpat.N.Age_Sex_Result.T.Positive",
      "HTS_TST_Malnutrition.N.Age_Sex_Result.T.Positive",
      "HTS_TST_MobileMod.N.Age_Sex_Result.T.Positive",
      "HTS_TST_OtherMod.N.Age_Sex_Result.T.Positive",
      "HTS_TST_OtherPITC.N.Age_Sex_Result.T.Positive",
      "HTS_TST_Pediatric.N.Age_Sex_Result.T.Positive",
      "HTS_TST_PMTCTPostANC1.N.Age_Sex_Result.T.Positive",
      "HTS_TST_POS.index_rate",
      "HTS_TST_POS.index_rate.psnu",
      "HTS_TST_POS.KeyPop.T",
      "HTS_TST_POS.T",
      "HTS_TST_STIClinic.N.Age_Sex_Result.T.Positive",
      "HTS_TST_VCT.N.Age_Sex_Result.T.Positive",
      "HTS_TST.Linkage.T",
      "HTS_TST.N.KeyPop_Result.T.Positive",
      "ID",
      "id",
      "id1",
      "id2",
      "in_region",
      "indicator_code",
      "indicatorCode",
      "is_array",
      "is_region",
      "key",
      "KeyPop",
      "kp_option_uid",
      "lastupdated",
      "level",
      "level_4_type",
      "level3name",
      "mech_code",
      "mechanism",
      "Mechanism",
      "mechanism_code",
      "mechanism_desc",
      "mechanismCode",
      "mechCode_supportType",
      "model_uid",
      "n",
      "name",
      "name1",
      "name2",
      "name3",
      "name4",
      "new.col",
      "num_den",
      "numerator_denominator",
      "numeric_15",
      "occurrence",
      "operating_unit",
      "org_unit",
      "org_unit_uid",
      "orgUnit",
      "orgunit",
      "ou",
      "ou_id",
      "partner",
      "partner_desc",
      "partner_id",
      "path",
      "percent",
      "period",
      "PLHIV.NA.Age/Sex/HIVStatus.T",
      "PMTCT_STAT.N.Age_Sex_KnownNewResult.T.NewPos",
      "primeid",
      "prioritization",
      "PSNU",
      "psnu",
      "psnu_type",
      "psnu_uid",
      "psnuid",
      "result_value",
      "resultstatus",
      "resultstatus_inclusive",
      "Rollup",
      "row_id",
      "setNames",
      "sex",
      "Sex",
      "sex_option_uid",
      "sheet",
      "sheet_name",
      "sheet_num",
      "sheet_num.test",
      "Site",
      "site_type",
      "site_uid",
      "snu1",
      "snu1_id",
      "st",
      "startdate",
      "Status",
      "storedby",
      "styleGuide",
      "submission_order",
      "submitted_fx",
      "support_type",
      "TB_STAT.N.Age_Sex_KnownNewPosNeg.T.NewPos",
      "tech_area",
      "technical_area",
      "template_order",
      "top_level",
      "TX_CURR_SUBNAT.N.Age/Sex/HIVStatus.T",
      "TX_CURR.N.Age_Sex_HIVStatus.T",
      "TX_CURR.N.Age_Sex_HIVStatus.T_1",
      "TX_NEW.N.Age_Sex_HIVStatus.T",
      "TX_NEW.N.EIDRate",
      "TX_NEW.N.IndexRate",
      "TX_NEW.N.KeyPop_HIVStatus.T",
      "TX_NEW.N.PMTCTRate",
      "TX_NEW.N.PostANC1Rate",
      "TX_NEW.N.prevDiagnosedRate",
      "TX_NEW.N.TBRate",
      "TX_NEW.N.VMMCRateNew",
      "TX.Retention.T",
      "Type",
      "type",
      "uid",
      "uidlevel3",
      "upload_timestamp",
      "valid_ages",
      "valid_ages.id",
      "valid_ages.name",
      "valid_ages.options",
      "valid_kps",
      "valid_kps.id",
      "valid_kps.name",
      "valid_kps.options",
      "valid_PSNUs",
      "valid_sexes",
      "valid_sexes.id",
      "valid_sexes.name",
      "valid_sexes.options",
      "value",
      "value_numeric",
      "value_type",
      "value.datapack",
      "valueRounded.datapack",
      "values",
      "VMMC_CIRC.N.Age_Sex_HIVStatus.T.Positive"
    )

  )
