#' @docType package
#' @name datapackr
#' @title Data Pack on R
#'
#' @description
#' datapackr: a grammar of Data Pack manipulation
#'
#'
#' datapackr is the engine behind PEPFAR Data Packs, a tool used annually to
#' aid PEPFAR Country Teams in setting targets for their annual Country
#' Operating Plan (COP).
#'
#' It has three main goals:
#'
#' \itemize{
#' \item Generate Data Packs, either at District or Site Level as directed.
#' \item Process and validate Data Packs submitted for review
#' \item Prepare Data Pack data for import into DATIM, the PEPFAR data collection database.
#' }
#'
#'
#'
if (getRversion() >= "2.15.1")
  utils::globalVariables(
    c(".",
      ".GRP",
      "age",
      "Age",
      "age_option_name",
      "age_option_uid",
      "age_uid",
      "AgeCoarse",
      "agency",
      "ancestors",
      "area_id",
      "ART_coverage",
      "as",
      "attribute_option",
      "attribute_option_combo",
      "attribute_option_combo_code",
      "attributeoptioncombo",
      "attributeOptionCombo",
      "calendar_quarter",
      "category_combo.id",
      "category_combo.name",
      "category_option_combo",
      "category_option.id",
      "category_option.name",
      "categoryoption",
      "categoryoption_specified",
      "categoryoptioncombo",
      "categoryOptionCombo",
      "categoryoptioncombo_id",
      "categoryoptioncombo_name",
      "categoryoptioncomboname",
      "categoryoptioncombouid",
      "categoryoptiongroup",
      "categoryOptions",
      "character_10",
      "character_11",
      "character_12",
      "character_13",
      "character_14",
      "character_5",
      "character_6",
      "character_7",
      "character_8",
      "character_9",
      "code",
      "col_name",
      "col_name",
      "col_name_new",
      "col_name_new",
      "col_type",
      "cop_year",
      "cop21_data_pack_schema",
      "correct_fx",
      "count",
      "country_name",
      "country_uid",
      "country_uids",
      "Crosswalk Dedupe",
      "Crosswalk Dedupe Resolution (FY22)",
      "Crosswalk Dedupe.updated",
      "Custom Crosswalk Dedupe Allocation (FY22) (% of DataPackTarget)",
      "Custom DSD Dedupe Allocation (FY22) (% of DataPackTarget)",
      "Custom TA Dedupe Allocation (FY22) (% of DataPackTarget)",
      "d2_default_session",
      "d2_session",
      "data_element",
      "data_element.id",
      "data_element.name",
      "data_pack_name",
      "data_structure",
      "dataelement",
      "dataElement",
      "dataelement_dsd",
      "dataelement_ta",
      "dataelement.y",
      "dataelementname",
      "dataelementuid",
      "DataPack",
      "datapack_cog",
      "datapack_disagg",
      "datapack_schema_group",
      "datapack_value",
      "DataPackTarget",
      "dataset",
      "dataSets",
      "DATIM",
      "datim_value",
      "Dedupe",
      "Deduplicated DSD Rollup",
      "Deduplicated DSD Rollup (FY22)",
      "Deduplicated TA Rollup",
      "Deduplicated TA Rollup (FY22)",
      "disagg_type",
      "distribution",
      "distribution_diff",
      "dp_psnu",
      "DREAMS",
      "DREAMS_SNU.Flag",
      "DSD",
      "DSD Dedupe",
      "DSD Dedupe Resolution (FY22)",
      "DSD Dedupe.updated",
      "DSD Duplicated Rollup",
      "DSD Duplicated Rollup",
      "DSD Duplicated Rollup.updated",
      "DSD_count",
      "duplicate_cols",
      "duplicate_cols",
      "duplicated_cols",
      "effect",
      "enddate",
      "fiscal_year",
      "formula",
      "formula_15",
      "formula.x",
      "formula.y",
      "funding_agency",
      "FY",
      "grp",
      "home_cell",
      "HTS_INDEX_COM.New.Pos.T",
      "HTS_INDEX_FAC.New.Pos.T",
      "HTS_INDEX.total",
      "hts_modality",
      "HTS_TST_POS.index_rate",
      "HTS_TST_POS.T",
      "HTS_TST.KP.Linkage.T",
      "HTS_TST.KP.Pos.T",
      "HTS_TST.Linkage.T",
      "id",
      "ID",
      "id_col",
      "index_issues",
      "indicator_code",
      "indicatorCode",
      "is_array",
      "is_valid",
      "issues.Deduplicated DSD Rollup",
      "issues.Deduplicated TA Rollup",
      "issues.Total Deduplicated Rollup",
      "key",
      "key_population",
      "KeyPop",
      "knownpos_ratio",
      "knownpos_ratio",
      "kp_option_name",
      "kp_option_uid",
      "lastupdated",
      "level",
      "level_4_type",
      "level3name",
      "MAX - Crosswalk Total",
      "MAX - DSD",
      "MAX - TA",
      "Max Deduplicated DSD Rollup",
      "Max Deduplicated TA Rollup",
      "Max Total Deduplicated Rollup",
      "mech_code",
      "mechanism",
      "mechanism_code",
      "mechanism_desc",
      "mechcode_supporttype",
      "mechCode_supportType",
      "Min Deduplicated DSD Rollup",
      "Min Deduplicated TA Rollup",
      "Min Total Deduplicated Rollup",
      "model_uid",
      "n",
      "name",
      "name3",
      "name4",
      "numerator_denominator",
      "numeric_15",
      "operating_unit",
      "org_unit",
      "organisationUnitGroups",
      "orgunit",
      "orgUnit",
      "ou",
      "ou_id",
      "partner",
      "partner_desc",
      "partner_id",
      "percent",
      "period",
      "period_dataset",
      "plhiv",
      "PLHIV.T_1",
      "PMTCT_EID.2mo.rate",
      "PMTCT_EID.N.12.T",
      "PMTCT_EID.N.2.T",
      "PMTCT_EID.T",
      "PMTCT_STAT.N.KnownPos.T",
      "PMTCT_STAT.N.New.Neg.T",
      "PMTCT_STAT.N.New.Pos.T",
      "PMTCT_STAT.N.Total",
      "pop",
      "POP_EST.T_1",
      "primeid",
      "prioritization",
      "psnu",
      "PSNU",
      "psnu_type",
      "psnu_uid",
      "psnuid",
      "PSNUxIM_value",
      "result_value",
      "resultstatus",
      "resultstatus_inclusive",
      "Rollup",
      "row_id",
      "schema",
      "setNames",
      "sex",
      "Sex",
      "sex_option_name",
      "sex_option_uid",
      "sex_uid",
      "sheet",
      "sheet_name",
      "sheet_num",
      "sheet_num.test",
      "snu1",
      "snu1_id",
      "startdate",
      "storedby",
      "styleGuide",
      "submission_order",
      "submitted_fx",
      "SUM - Crosswalk Total",
      "SUM - DSD",
      "SUM - TA",
      "support_type",
      "TA",
      "TA Dedupe",
      "TA Dedupe Resolution (FY22)",
      "TA Dedupe.updated",
      "TA Duplicated Rollup",
      "TA Duplicated Rollup",
      "TA Duplicated Rollup.updated",
      "TA_count",
      "target_col",
      "target_value",
      "TB_STAT.N.KnownPos.T",
      "TB_STAT.N.New.Neg.T",
      "TB_STAT.N.New.Pos.T",
      "TB_STAT.N.Total",
      "tech_area",
      "technical_area",
      "template_order",
      "top_level",
      "Total Deduplicated Rollup",
      "Total Deduplicated Rollup (FY22)",
      "Total Duplicated Rollup",
      "Total Duplicated Rollup.updated",
      "Total_count",
      "total_distribution",
      "tx_curr",
      "TX_CURR_SUBNAT.T_1",
      "TX_CURR.T",
      "TX_CURR.T_1",
      "TX_NEW.KP.T",
      "TX_NEW.N.Age_Sex_HIVStatus.T",
      "TX_NEW.N.EIDRate",
      "TX_NEW.N.IndexRate",
      "TX_NEW.N.PMTCTRate",
      "TX_NEW.N.PostANC1Rate",
      "TX_NEW.N.prevDiagnosedRate",
      "TX_NEW.N.TBRate",
      "TX_NEW.N.VMMCRateNew",
      "TX_NEW.T",
      "TX_NEW.T",
      "TX.Retention.T",
      "type",
      "uid",
      "uidlevel3",
      "upload_timestamp",
      "V1",
      "valid_ages",
      "valid_ages.id",
      "valid_ages.name",
      "valid_ages.options",
      "valid_kps",
      "valid_kps.id",
      "valid_kps.name",
      "valid_kps.options",
      "valid_PSNUs",
      "valid_sexes",
      "valid_sexes.id",
      "valid_sexes.name",
      "valid_sexes.options",
      "value",
      "value_numeric",
      "value_type",
      "values",
      "VMMC_CIRC.indeterminateRate",
      "VMMC_CIRC.Neg.T",
      "VMMC_CIRC.Pos.T",
      "VMMC_CIRC.T",
      "VMMC_CIRC.Unk.T",
      "warn"
    )
  )
