#' @docType package
#' @name datapackr
#' @title Data Pack on R
#'
#' datapackr: a grammar of Data Pack manipulation
#'
#'
#' datapackr is the engine behind PEPFAR Data Packs, a tool used annually to
#' aid PEPFAR Country Teams in setting targets for their annual Country
#' Operating Plan (COP).
#'
#' It has three main goals:
#'
#' \itemize{
#' \item Generate Data Packs, either at District or Site Level as directed.
#' \item Process and validate Data Packs submitted for review
#' \item Prepare Data Pack data for import into DATIM, the PEPFAR data collection database.
#' }
#'
#'

if (getRversion() >= "2.15.1")
  utils::globalVariables(
    c(
      ".",
      "Age",
      "Agency",
      "agency",
      "ancestors",
      "attributeoptioncombo",
      "attributeOptionCombo",
      "categoryoptioncombo",
      "categoryOptionCombo",
      "categoryoptioncombouid",
      "categoryOptionGroups",
      "categoryOptions",
      "CoarseAge",
      "code",
      "col_type",
      "colType",
      "community",
      "country",
      "Country",
      "country_name",
      "countryName",
      "country_uid",
      "country_uids",
      "countryUID",
      "Currently_in_DATIM",
      "dataelement",
      "dataElement",
      "dataelementuid",
      "DataPack_name",
      "data_pack_name",
      "DataPackSiteID",
      "DataPackTarget",
      "dataset",
      "disag",
      "distribution",
      "Distribution Check",
      "dp_psnu",
      "end_date",
      "enddate",
      "endDate",
      "EndDate",
      "facility",
      "groupSets",
      "grp_total",
      "HQID",
      "id",
      "IM",
      "IMPATT.PRIORITY_SNU.20T",
      "indicator",
      "Indicator",
      "indicator_code",
      "indicatorCode",
      "in_region",
      "is_region",
      "isMil",
      "KeyPop",
      "level",
      "level3name",
      "level4name",
      "mechanism",
      "mechanismCode",
      "mechanismid",
      "Mechanism",
      "mech_code",
      "mil_level",
      "mil_psnu",
      "mil_psnu_uid",
      "milPSNU",
      "milPSNU_in_DATIM",
      "milPSNUuid",
      "model_uid",
      "msg",
      "n",
      "name",
      "name3",
      "name4",
      "newMech",
      "newValue",
      "Numerator / Denominator",
      "oldMech",
      "Old Mechanism",
      "operating_unit",
      "operating_unit_id",
      "order_check",
      "organisationunituid",
      "organisation_unit_id",
      "organisation_unit_name",
      "organisationUnitGroups",
      "organisationUnits",
      "orgunit",
      "orgUnit",
      "ou",
      "packageVersion",
      "partner",
      "period",
      "planning",
      "primeid",
      "PrimePartner",
      "prioritization",
      "Prioritizing_at_Natl_or_SNU",
      "psnu",
      "PSNU",
      "psnuid",
      "psnu_type",
      "psnu_uid",
      "row_id",
      "setNames",
      "Sex",
      "sheet_name",
      "sheet_num",
      "sheets",
      "Site",
      "site_schema",
      "siteID",
      "site_uid",
      "siteValue",
      "site_tool_label",
      "site_type",
      "start_date",
      "startdate",
      "startDate",
      "StartDate",
      "Status",
      "str",
      "submission_order",
      "Support Type",
      "Technical Area",
      "template_order",
      "typeOptions",
      "type",
      "Type",
      "uid",
      "uidlevel3",
      "validAges",
      "validKPs",
      "validSexes",
      "value",
      "wb",
      "weight"
    )
    
  )