#' @export
#' @title getNumeratorDenominator
#' 
#' @description 
#' Map Numerator and Denominator to dataElement id
#' 
#' @param dataElements List of dataElements to filter against. (Optional)
#'
#' @param d2_session the object with handle information generated by the login function
#' 
#' @return Dataframe of Numerator and Denominators mapped to dataElements
#' 
getNumeratorDenominator <- function(dataElements = NULL, d2_session = parent.frame()$d2_default_session) {

     r <-  datimutils::getDataElementGroupSets(values = "lD2x0c8kywj",
                                 by = "id",
                                 fields = "id,name,dataElementGroups[name,dataElements[id]]",
                                          d2_session = d2_session
   )

  r <- r[["dataElementGroups"]][[1]]
  r <- tidyr::unnest(r, cols = c(dataElements))
  r <- dplyr::distinct(r)
  r <- dplyr::select(r, dataElement = id,
                  numerator_denominator = name )
  
  if (!is.null(dataElements)) {
    r %<>%
      dplyr::filter(dataElement %in% dataElements)
  }
  
  return(r)
  
}
