#' @export
#' @title getTechArea
#' 
#' @description 
#' Map Tech Area to dataElement id
#' 
#' @param dataElements List of dataElements to filter against. (Optional)
#' @param d2_session the login objdct that contains handle info. Generated by the login function
#'
#' @return Dataframe of Tech Areas mapped to dataElements
#' 
getTechArea <- function(dataElements = NULL, d2_session = parent.frame()$d2_default_session) {

   r <-  datimutils::getDataElementGroupSets(values = "LxhLO68FcXm",
                                 by = "id",
                                 fields = "id,name,dataElementGroups[name,dataElements[id]]",
                                          d2_session = d2_session
   )

  r <- r[["dataElementGroups"]][[1]]
  r <- tidyr::unnest(r, cols = c(dataElements))
  r <- dplyr::distinct(r)
  r <- dplyr::select(r, dataElement = id,
                  tech_area = name )


  if (!is.null(dataElements)) {
    r %<>%
      dplyr::filter(dataElement %in% dataElements)
  }

  return(r)
}
